title: Barravar Git Repository
email: admin@barravar.com.br
description: >-
  Barravar Git Repository
baseurl: ""
url: https://git.barravar.com.br
repo_name: barravar
twitter_username: barravar
github_username: barravar
github:
  zip_url: https://git.barravar.com.br/download.zip
  repository_url: https://git.barravar.com.br

# Build settings
#theme: minima
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
